#!/bin/bash

# Rebuild frontend with correct API endpoints
# This script updates the frontend to use the correct backend port (8888)

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Detect the actual directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE_DIR="$SCRIPT_DIR"
FRONTEND_DIR="$BASE_DIR/frontend"

echo -e "${BLUE}=== Rebuilding Frontend ===${NC}"
echo "Date: $(date)"
echo "Base Directory: $BASE_DIR"
echo ""

# 1. Check if frontend directory exists
if [ ! -d "$FRONTEND_DIR" ]; then
    echo -e "${RED}ERROR: Frontend directory not found at $FRONTEND_DIR${NC}"
    exit 1
fi

cd "$FRONTEND_DIR"

# 2. Stop frontend service if running
echo -e "${BLUE}Step 1: Stopping frontend service...${NC}"
if lsof -i :5173 >/dev/null 2>&1; then
    echo "Stopping frontend on port 5173..."
    lsof -ti :5173 | xargs -r kill 2>/dev/null
    sleep 2
fi
echo -e "${GREEN}✓${NC} Frontend stopped"
echo ""

# 3. Pull latest changes
echo -e "${BLUE}Step 2: Pulling latest changes...${NC}"
cd "$BASE_DIR"
git pull || {
    echo -e "${YELLOW}Warning: Could not pull latest changes${NC}"
}
echo ""

# 4. Update frontend configuration
echo -e "${BLUE}Step 3: Updating frontend configuration...${NC}"
cd "$FRONTEND_DIR"

# Create/update .env file with correct ports
cat > .env << EOF
# Frontend Environment Variables
# Auto-generated by rebuild-frontend.sh

# API Endpoints - Using correct ports for Ubuntu deployment
VITE_BASE_URL=http://localhost
VITE_BACKEND_URL=http://localhost:8888
VITE_LLM_URL=http://localhost:8001
VITE_EMBEDDING_URL=http://localhost:8010
VITE_RERANKING_URL=http://localhost:8012

# WebSocket Configuration
VITE_WS_ENABLED=false
VITE_WS_URL=ws://localhost:8888

# Feature Flags
VITE_FEATURE_FILE_UPLOAD=true
VITE_FEATURE_WEBSOCKET=false
VITE_FEATURE_STREAMING=true
VITE_FEATURE_KNOWLEDGE_BASE=true

# Environment
VITE_APP_ENV=production
EOF

echo -e "${GREEN}✓${NC} Configuration updated"
echo ""

# 5. Check Node.js and npm
echo -e "${BLUE}Step 4: Checking Node.js environment...${NC}"
if ! command -v node >/dev/null 2>&1; then
    echo -e "${RED}ERROR: Node.js is not installed${NC}"
    echo "Please install Node.js first:"
    echo "  curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
    echo "  sudo apt-get install -y nodejs"
    exit 1
fi

echo "Node version: $(node --version)"
echo "npm version: $(npm --version)"
echo ""

# 6. Install dependencies
echo -e "${BLUE}Step 5: Installing dependencies...${NC}"
if [ ! -d "node_modules" ] || [ ! -f "package-lock.json" ]; then
    echo "Installing npm packages..."
    npm install --legacy-peer-deps || {
        echo -e "${RED}ERROR: Failed to install dependencies${NC}"
        exit 1
    }
else
    echo "Updating npm packages..."
    npm ci --legacy-peer-deps || npm install --legacy-peer-deps
fi
echo -e "${GREEN}✓${NC} Dependencies installed"
echo ""

# 7. Build frontend
echo -e "${BLUE}Step 6: Building frontend...${NC}"
echo "This may take a few minutes..."

# Clear old build
rm -rf dist

# Build with error tolerance for TypeScript issues
TSC_COMPILE_ON_ERROR=true npm run build || {
    echo -e "${YELLOW}Build had some warnings, trying alternative build...${NC}"

    # Try direct Vite build
    npx vite build --mode production || {
        echo -e "${RED}ERROR: Build failed${NC}"
        echo -e "${YELLOW}Frontend will run in development mode instead${NC}"

        # Mark that we should use dev mode
        touch .use-dev-mode

        echo -e "${YELLOW}Frontend will be started in development mode${NC}"
    }
}

if [ -d "dist" ]; then
    echo -e "${GREEN}✓${NC} Frontend built successfully"
    echo "Build output: $(du -sh dist | cut -f1) in $(ls -1 dist | wc -l) files"
    rm -f .use-dev-mode 2>/dev/null
else
    echo -e "${YELLOW}⚠${NC} Build directory not created, will use development mode"
fi
echo ""

# 8. Start frontend
echo -e "${BLUE}Step 7: Starting frontend...${NC}"

LOG_DIR="$BASE_DIR/logs"
mkdir -p "$LOG_DIR"

if [ -f ".use-dev-mode" ] || [ ! -d "dist" ]; then
    echo -e "${YELLOW}Starting in development mode...${NC}"

    # Start dev server in background
    nohup npm run dev -- --host 0.0.0.0 --port 5173 > "$LOG_DIR/frontend-dev.log" 2>&1 &
    FRONTEND_PID=$!

    echo "Development server starting (PID: $FRONTEND_PID)..."
    sleep 5

    if ps -p $FRONTEND_PID > /dev/null; then
        echo -e "${GREEN}✓${NC} Frontend development server is running"
    else
        echo -e "${RED}✗${NC} Failed to start development server"
        tail -20 "$LOG_DIR/frontend-dev.log"
        exit 1
    fi
else
    echo "Starting production server..."

    # First try Python (most reliable)
    if command -v python3 >/dev/null 2>&1; then
        echo "Using Python http.server..."
        cd dist
        nohup python3 -m http.server 5173 --bind 0.0.0.0 > "$LOG_DIR/frontend-prod.log" 2>&1 &
        FRONTEND_PID=$!
        cd ..
        echo "Started Python http.server (PID: $FRONTEND_PID)..."
    # Then try npx serve (ensures we use npm's serve)
    elif npm list -g serve >/dev/null 2>&1 || npm list serve >/dev/null 2>&1; then
        echo "Using npx serve..."
        nohup npx serve dist -l 5173 -n > "$LOG_DIR/frontend-prod.log" 2>&1 &
        FRONTEND_PID=$!
        echo "Started npx serve (PID: $FRONTEND_PID)..."
    # Try Node.js static server
    elif command -v node >/dev/null 2>&1; then
        echo "Creating Node.js static server..."
        cat > serve-dist.js << 'EOF'
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 5173;
const DIST_DIR = path.join(__dirname, 'dist');

const mimeTypes = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'application/font-woff',
  '.woff2': 'application/font-woff2',
  '.ttf': 'application/font-ttf',
  '.eot': 'application/vnd.ms-fontobject'
};

const server = http.createServer((req, res) => {
  let filePath = path.join(DIST_DIR, req.url === '/' ? 'index.html' : req.url);

  // Handle SPA routing - serve index.html for all routes
  if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
    filePath = path.join(DIST_DIR, 'index.html');
  }

  fs.readFile(filePath, (err, content) => {
    if (err) {
      res.writeHead(404);
      res.end('Not found');
      return;
    }

    const ext = path.extname(filePath);
    const contentType = mimeTypes[ext] || 'application/octet-stream';
    res.writeHead(200, { 'Content-Type': contentType });
    res.end(content);
  });
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Frontend server running at http://localhost:${PORT}/`);
});
EOF
        nohup node serve-dist.js > "$LOG_DIR/frontend-prod.log" 2>&1 &
        FRONTEND_PID=$!
        echo "Started Node.js static server (PID: $FRONTEND_PID)..."
    else
        echo -e "${RED}ERROR: No suitable static server found${NC}"
        echo "Python3 or Node.js is required to serve the frontend"
        exit 1
    fi

    sleep 3

    if ps -p $FRONTEND_PID > /dev/null; then
        echo -e "${GREEN}✓${NC} Frontend production server is running"
    else
        echo -e "${RED}✗${NC} Failed to start production server"
        tail -20 "$LOG_DIR/frontend-prod.log"
        exit 1
    fi
fi

echo ""
echo -e "${BLUE}=== Frontend Rebuild Complete ===${NC}"
echo ""
echo -e "${GREEN}Frontend is now running with updated configuration:${NC}"
echo "  URL: http://localhost:5173"
echo "  Backend API: http://localhost:8888"
echo "  LLM Service: http://localhost:8001"
echo "  Embedding: http://localhost:8010"
echo "  Reranking: http://localhost:8012"
echo ""
echo "To check status:"
echo "  lsof -i :5173"
echo ""
echo "To view logs:"
if [ -f ".use-dev-mode" ] || [ ! -d "dist" ]; then
    echo "  tail -f $LOG_DIR/frontend-dev.log"
else
    echo "  tail -f $LOG_DIR/frontend-prod.log"
fi
echo ""
echo -e "${YELLOW}Note: Clear your browser cache if you still see old configuration${NC}"