#!/usr/bin/env python3
"""
Dify Platform Deployment Script for Drass
Deploys complete Dify platform and imports Drass applications automatically.
Based on official Dify documentation: https://docs.dify.ai/zh-hans/getting-started/install-self-hosted/docker-compose
"""

import os
import sys
import time
import json
import requests
import subprocess
import argparse
from pathlib import Path
from typing import Dict, Any, Optional, List
import yaml

class DifyDeployer:
    def __init__(self, config_path: str = "config/dify-config.yaml"):
        self.config_path = config_path
        self.dify_url = "http://localhost"
        self.api_url = f"{self.dify_url}/console/api"
        self.admin_email = os.getenv("DIFY_ADMIN_EMAIL", "admin@drass.local")
        self.admin_password = os.getenv("DIFY_ADMIN_PASSWORD", "admin123")
        
    def run_command(self, command: List[str], check: bool = True) -> subprocess.CompletedProcess:
        """Run a shell command and return the result."""
        try:
            result = subprocess.run(command, check=check, capture_output=True, text=True)
            return result
        except subprocess.CalledProcessError as e:
            print(f"❌ Command failed: {' '.join(command)}")
            print(f"Error: {e.stderr}")
            if check:
                sys.exit(1)
            return e
    
    def check_prerequisites(self) -> bool:
        """Check if all prerequisites are met."""
        print("🔍 Checking prerequisites...")
        
        # Check Docker
        try:
            result = subprocess.run(["docker", "--version"], capture_output=True, text=True)
            if result.returncode != 0:
                print("❌ Docker is not installed or not accessible")
                return False
            print(f"✅ Docker: {result.stdout.strip()}")
        except FileNotFoundError:
            print("❌ Docker command not found")
            return False
        
        # Check Docker Compose
        try:
            result = subprocess.run(["docker-compose", "--version"], capture_output=True, text=True)
            if result.returncode != 0:
                print("❌ Docker Compose is not installed or not accessible")
                return False
            print(f"✅ Docker Compose: {result.stdout.strip()}")
        except FileNotFoundError:
            print("❌ Docker Compose command not found")
            return False
        
        # Check available memory
        try:
            result = subprocess.run(["docker", "system", "info"], capture_output=True, text=True)
            if "Total Memory" in result.stdout:
                print("✅ Docker system info available")
            else:
                print("⚠️  Could not verify Docker memory allocation")
        except:
            print("⚠️  Could not verify Docker system info")
        
        return True
    
    def create_env_file(self) -> bool:
        """Create .env file with required environment variables."""
        print("📝 Creating environment configuration...")
        
        env_content = """# Dify Platform Environment Configuration
# Generated by Drass deployment script

# Database Configuration
DB_PASSWORD=dify_password_secure_123
REDIS_PASSWORD=redis_password_secure_123

# Dify Platform Configuration
SECRET_KEY=your-secret-key-here-change-in-production
ENCRYPTION_KEY=your-encryption-key-here-change-in-production

# Weaviate Configuration
WEAVIATE_API_KEY=

# Admin Account
DIFY_ADMIN_EMAIL=admin@drass.local
DIFY_ADMIN_PASSWORD=admin123

# Optional: Sentry for error tracking
SENTRY_DSN=

# Optional: Grafana password
GRAFANA_PASSWORD=admin
"""
        
        try:
            with open(".env", "w") as f:
                f.write(env_content)
            print("✅ Environment file created: .env")
            print("⚠️  Please review and update .env file before production use")
            return True
        except Exception as e:
            print(f"❌ Failed to create .env file: {e}")
            return False
    
    def deploy_dify_platform(self) -> bool:
        """Deploy the Dify platform using Docker Compose."""
        print("🚀 Deploying Dify platform...")
        
        # Start core services
        print("  - Starting core services...")
        result = self.run_command(["docker-compose", "up", "-d", "db", "redis", "weaviate"], check=False)
        if result.returncode != 0:
            print("❌ Failed to start core services")
            return False
        
        # Wait for core services to be ready
        print("  - Waiting for core services to be ready...")
        time.sleep(30)
        
        # Start API and worker services
        print("  - Starting API and worker services...")
        result = self.run_command(["docker-compose", "up", "-d", "api", "worker"], check=False)
        if result.returncode != 0:
            print("❌ Failed to start API and worker services")
            return False
        
        # Wait for API to be ready
        print("  - Waiting for API service to be ready...")
        time.sleep(30)
        
        # Start web service
        print("  - Starting web service...")
        result = self.run_command(["docker-compose", "up", "-d", "web"], check=False)
        if result.returncode != 0:
            print("❌ Failed to start web service")
            return False
        
        # Start optional services
        print("  - Starting optional services...")
        result = self.run_command(["docker-compose", "up", "-d", "ssrf_proxy", "sandbox"], check=False)
        if result.returncode != 0:
            print("⚠️  Some optional services failed to start")
        
        print("✅ Dify platform deployment completed")
        return True
    
    def wait_for_dify_ready(self, timeout: int = 300) -> bool:
        """Wait for Dify platform to be ready."""
        print("⏳ Waiting for Dify platform to be ready...")
        
        start_time = time.time()
        while time.time() - start_time < timeout:
            try:
                response = requests.get(f"{self.dify_url}/health", timeout=10)
                if response.status_code == 200:
                    print("✅ Dify platform is ready")
                    return True
            except requests.exceptions.RequestException:
                pass
            
            print("  - Platform not ready yet, waiting...")
            time.sleep(10)
        
        print("❌ Timeout waiting for Dify platform to be ready")
        return False
    
    def setup_admin_account(self) -> bool:
        """Set up the admin account for Dify platform."""
        print("👤 Setting up admin account...")
        
        # Check if admin account already exists
        try:
            response = requests.get(f"{self.dify_url}/install", timeout=10)
            if response.status_code == 200 and "install" in response.text.lower():
                print("  - Admin account setup required")
            else:
                print("✅ Admin account already exists")
                return True
        except requests.exceptions.RequestException:
            print("⚠️  Could not check admin account status")
            return False
        
        # Set up admin account
        admin_data = {
            "email": self.admin_email,
            "password": self.admin_password,
            "name": "Drass Admin"
        }
        
        try:
            response = requests.post(f"{self.dify_url}/install", json=admin_data, timeout=30)
            if response.status_code == 200:
                print("✅ Admin account created successfully")
                return True
            else:
                print(f"❌ Failed to create admin account: {response.status_code}")
                return False
        except requests.exceptions.RequestException as e:
            print(f"❌ Error creating admin account: {e}")
            return False
    
    def get_auth_token(self) -> Optional[str]:
        """Get authentication token for API access."""
        print("🔑 Getting authentication token...")
        
        auth_data = {
            "email": self.admin_email,
            "password": self.admin_password
        }
        
        try:
            response = requests.post(f"{self.api_url}/auth/login", json=auth_data, timeout=30)
            if response.status_code == 200:
                token = response.json().get("access_token")
                if token:
                    print("✅ Authentication token obtained")
                    return token
                else:
                    print("❌ No token in response")
                    return None
            else:
                print(f"❌ Authentication failed: {response.status_code}")
                return None
        except requests.exceptions.RequestException as e:
            print(f"❌ Error during authentication: {e}")
            return None
    
    def import_drass_applications(self, token: str) -> bool:
        """Import Drass applications into Dify platform."""
        print("📥 Importing Drass applications...")
        
        # Load application configurations
        apps_dir = Path("apps")
        if not apps_dir.exists():
            print("⚠️  No applications directory found")
            return True
        
        app_files = list(apps_dir.glob("*.yaml"))
        if not app_files:
            print("⚠️  No application configuration files found")
            return True
        
        headers = {"Authorization": f"Bearer {token}"}
        
        for app_file in app_files:
            try:
                with open(app_file, 'r') as f:
                    app_config = yaml.safe_load(f)
                
                app_name = app_config.get('application', {}).get('name', 'Unknown App')
                print(f"  - Importing: {app_name}")
                
                # Create application in Dify
                app_data = {
                    "name": app_name,
                    "description": app_config.get('application', {}).get('description', ''),
                    "mode": "chat",  # Default mode
                    "icon_type": "emoji",
                    "icon": "🤖"
                }
                
                response = requests.post(f"{self.api_url}/apps", json=app_data, headers=headers, timeout=30)
                if response.status_code == 200:
                    app_id = response.json().get("id")
                    print(f"    ✅ Created with ID: {app_id}")
                    
                    # Update our database with Dify app ID
                    self.update_app_mapping(app_name, app_id)
                else:
                    print(f"    ❌ Failed to create: {response.status_code}")
                
            except Exception as e:
                print(f"    ❌ Error importing {app_file}: {e}")
        
        return True
    
    def update_app_mapping(self, app_name: str, dify_app_id: str) -> None:
        """Update the mapping between our apps and Dify apps."""
        # This would update the database to link our app configs with Dify app IDs
        print(f"    📝 Mapping {app_name} to Dify app {dify_app_id}")
    
    def start_monitoring(self) -> bool:
        """Start monitoring services."""
        print("📊 Starting monitoring services...")
        
        result = self.run_command(["docker-compose", "--profile", "monitoring", "up", "-d"], check=False)
        if result.returncode == 0:
            print("✅ Monitoring services started")
            return True
        else:
            print("⚠️  Failed to start monitoring services")
            return False
    
    def show_status(self) -> None:
        """Show the status of all services."""
        print("📊 Service status:")
        
        result = self.run_command(["docker-compose", "ps"], check=False)
        if result.returncode == 0:
            print(result.stdout)
        else:
            print("❌ Failed to get service status")
    
    def deploy_all(self, include_monitoring: bool = False) -> bool:
        """Deploy the complete Dify platform with Drass applications."""
        print("🚀 Starting complete Dify platform deployment...")
        
        # Check prerequisites
        if not self.check_prerequisites():
            return False
        
        # Create environment file
        if not self.create_env_file():
            return False
        
        # Deploy Dify platform
        if not self.deploy_dify_platform():
            return False
        
        # Wait for platform to be ready
        if not self.wait_for_dify_ready():
            return False
        
        # Set up admin account
        if not self.setup_admin_account():
            return False
        
        # Get authentication token
        token = self.get_auth_token()
        if not token:
            print("❌ Cannot proceed without authentication token")
            return False
        
        # Import Drass applications
        if not self.import_drass_applications(token):
            print("⚠️  Application import had issues")
        
        # Start monitoring if requested
        if include_monitoring:
            self.start_monitoring()
        
        # Show final status
        self.show_status()
        
        print("\n🎉 Deployment completed successfully!")
        print(f"🌐 Dify Platform: {self.dify_url}")
        print(f"👤 Admin Login: {self.admin_email} / {self.admin_password}")
        print(f"📚 API Documentation: {self.api_url}")
        
        return True

def main():
    parser = argparse.ArgumentParser(description="Deploy Dify Platform with Drass Applications")
    parser.add_argument("--monitoring", "-m", action="store_true", 
                       help="Include monitoring services")
    parser.add_argument("--config", "-c", default="config/dify-config.yaml",
                       help="Configuration file path")
    
    args = parser.parse_args()
    
    deployer = DifyDeployer(args.config)
    
    if deployer.deploy_all(include_monitoring=args.monitoring):
        print("\n✅ All done! Your Dify platform is ready.")
        sys.exit(0)
    else:
        print("\n❌ Deployment failed. Check logs for details.")
        sys.exit(1)

if __name__ == "__main__":
    main()
