#!/usr/bin/env python3
"""Unified deployment script for Drass Compliance Assistant."""

import sys
import os
import subprocess
import time
from pathlib import Path
from typing import Dict, Any, Optional, List
from abc import ABC, abstractmethod
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from rich.console import Console
    from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
    from rich.table import Table
    from rich.panel import Panel
    from rich.live import Live
    from rich import print as rprint
    import click
    import yaml
except ImportError:
    print("Error: Required packages not installed.")
    print("Please install: pip install rich click pyyaml")
    sys.exit(1)

from deployment.scripts.utils.config_loader import ConfigLoader, ConfigValidator
from deployment.scripts.utils.config_models import Config


console = Console()


class DeploymentError(Exception):
    """Deployment related errors."""
    pass


class BaseDeployer(ABC):
    """Base class for deployment strategies."""

    def __init__(self, config: Config):
        """Initialize deployer with configuration.

        Args:
            config: Deployment configuration
        """
        self.config = config
        self.services_status = {}

    @abstractmethod
    def deploy_services(self) -> None:
        """Deploy all services."""
        pass

    @abstractmethod
    def check_health(self) -> Dict[str, bool]:
        """Check health of deployed services."""
        pass

    @abstractmethod
    def cleanup(self) -> None:
        """Cleanup resources."""
        pass

    def generate_env_file(self, path: Path = Path(".env")) -> None:
        """Generate .env file from configuration.

        Args:
            path: Path to save .env file
        """
        env_vars = self.config.to_env()
        with open(path, "w") as f:
            f.write("# Generated by Drass Deploy\n")
            f.write(f"# {datetime.now().isoformat()}\n\n")
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")
        console.print(f"[green]✅ Generated .env file: {path}[/green]")


class DockerComposeDeployer(BaseDeployer):
    """Deploy using Docker Compose."""

    def deploy_services(self) -> None:
        """Deploy services using Docker Compose."""
        console.print("[cyan]Starting Docker Compose deployment...[/cyan]")

        # Generate docker-compose.yml
        self._generate_compose_file()

        # Pull images
        self._pull_images()

        # Start services
        self._start_services()

    def _generate_compose_file(self) -> None:
        """Generate docker-compose.yml from configuration."""
        compose_config = {
            "version": "3.8",
            "services": {},
            "networks": {
                "drass-network": {
                    "driver": "bridge"
                }
            },
            "volumes": {
                "postgres-data": {},
                "redis-data": {},
                "chromadb-data": {},
                "app-data": {}
            }
        }

        # PostgreSQL
        if self.config.services.database.type == "postgresql":
            compose_config["services"]["postgres"] = {
                "image": "postgres:15-alpine",
                "environment": {
                    "POSTGRES_USER": self.config.services.database.user or "postgres",
                    "POSTGRES_PASSWORD": self.config.services.database.password or "postgres",
                    "POSTGRES_DB": self.config.services.database.database
                },
                "ports": ["5432:5432"],
                "volumes": ["postgres-data:/var/lib/postgresql/data"],
                "networks": ["drass-network"],
                "healthcheck": {
                    "test": ["CMD-SHELL", "pg_isready -U postgres"],
                    "interval": "10s",
                    "timeout": "5s",
                    "retries": 5
                }
            }

        # Redis
        if self.config.services.cache and self.config.services.cache.type == "redis":
            compose_config["services"]["redis"] = {
                "image": "redis:7-alpine",
                "ports": ["6379:6379"],
                "volumes": ["redis-data:/data"],
                "networks": ["drass-network"],
                "healthcheck": {
                    "test": ["CMD", "redis-cli", "ping"],
                    "interval": "10s",
                    "timeout": "5s",
                    "retries": 5
                }
            }

        # ChromaDB
        if self.config.services.vector_store.type == "chromadb":
            compose_config["services"]["chromadb"] = {
                "image": "chromadb/chroma:latest",
                "ports": ["8000:8000"],
                "volumes": ["chromadb-data:/chroma/chroma"],
                "networks": ["drass-network"],
                "environment": {
                    "IS_PERSISTENT": "TRUE",
                    "PERSIST_DIRECTORY": "/chroma/chroma"
                }
            }

        # Embedding service
        if self.config.services.embedding.provider == "local":
            compose_config["services"]["embedding-service"] = {
                "build": {
                    "context": "./services/embedding-service",
                    "dockerfile": "Dockerfile"
                },
                "ports": ["8002:8002"],
                "networks": ["drass-network"],
                "environment": {
                    "MODEL_NAME": self.config.services.embedding.model,
                    "DEVICE": self.config.services.embedding.device
                },
                "depends_on": ["redis"] if self.config.services.cache else []
            }

        # Reranking service
        if self.config.services.reranking and self.config.services.reranking.enabled:
            compose_config["services"]["reranking-service"] = {
                "build": {
                    "context": "./services/reranking-service",
                    "dockerfile": "Dockerfile"
                },
                "ports": ["8004:8004"],
                "networks": ["drass-network"],
                "environment": {
                    "MODEL_NAME": self.config.services.reranking.model,
                    "DEVICE": self.config.services.reranking.device
                }
            }

        # Document processor
        if self.config.services.document_processor and self.config.services.document_processor.enabled:
            compose_config["services"]["doc-processor"] = {
                "build": {
                    "context": "./services/doc-processor",
                    "dockerfile": "Dockerfile"
                },
                "ports": ["8003:8003"],
                "networks": ["drass-network"],
                "volumes": ["app-data:/app/data"],
                "environment": {
                    "MAX_FILE_SIZE": self.config.services.document_processor.max_file_size,
                    "OCR_ENABLED": str(self.config.services.document_processor.ocr_enabled)
                }
            }

        # Main application
        compose_config["services"]["main-app"] = {
            "build": {
                "context": "./services/main-app",
                "dockerfile": "Dockerfile"
            },
            "ports": [f"{self.config.application.main_app.port}:8000"],
            "networks": ["drass-network"],
            "volumes": ["app-data:/app/data"],
            "env_file": ".env",
            "depends_on": self._get_dependencies(),
            "healthcheck": {
                "test": ["CMD", "curl", "-f", "http://localhost:8000/health"],
                "interval": "30s",
                "timeout": "10s",
                "retries": 3
            }
        }

        # Frontend
        compose_config["services"]["frontend"] = {
            "build": {
                "context": "./frontend",
                "dockerfile": "Dockerfile",
                "args": {
                    "VITE_API_BASE": self.config.application.frontend.api_base
                }
            },
            "ports": [f"{self.config.application.frontend.port}:80"],
            "networks": ["drass-network"],
            "depends_on": ["main-app"]
        }

        # Save compose file
        with open("docker-compose.generated.yml", "w") as f:
            yaml.dump(compose_config, f, default_flow_style=False, sort_keys=False)

        console.print("[green]✅ Generated docker-compose.yml[/green]")

    def _get_dependencies(self) -> List[str]:
        """Get service dependencies for main app."""
        deps = []
        if self.config.services.database.type == "postgresql":
            deps.append("postgres")
        if self.config.services.cache and self.config.services.cache.type == "redis":
            deps.append("redis")
        if self.config.services.vector_store.type == "chromadb":
            deps.append("chromadb")
        if self.config.services.embedding.provider == "local":
            deps.append("embedding-service")
        if self.config.services.reranking and self.config.services.reranking.enabled:
            deps.append("reranking-service")
        return deps

    def _pull_images(self) -> None:
        """Pull Docker images."""
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            console=console
        ) as progress:
            task = progress.add_task("Pulling Docker images...", total=None)
            subprocess.run(
                ["docker-compose", "-f", "docker-compose.generated.yml", "pull"],
                check=False,
                capture_output=True
            )
            progress.update(task, completed=True)

    def _start_services(self) -> None:
        """Start Docker Compose services."""
        console.print("[cyan]Starting services...[/cyan]")
        result = subprocess.run(
            ["docker-compose", "-f", "docker-compose.generated.yml", "up", "-d"],
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            raise DeploymentError(f"Failed to start services: {result.stderr}")

        console.print("[green]✅ Services started[/green]")

    def check_health(self) -> Dict[str, bool]:
        """Check health of Docker services."""
        health_status = {}

        result = subprocess.run(
            ["docker-compose", "-f", "docker-compose.generated.yml", "ps", "--format", "json"],
            capture_output=True,
            text=True
        )

        if result.returncode == 0 and result.stdout:
            import json
            try:
                services = json.loads(result.stdout)
                for service in services:
                    health_status[service.get("Service", "unknown")] = \
                        service.get("State", "").lower() == "running"
            except json.JSONDecodeError:
                # Fallback to simple check
                for line in result.stdout.split('\n'):
                    if 'Up' in line:
                        parts = line.split()
                        if parts:
                            health_status[parts[0]] = True

        return health_status

    def cleanup(self) -> None:
        """Stop and remove Docker containers."""
        console.print("[yellow]Stopping services...[/yellow]")
        subprocess.run(
            ["docker-compose", "-f", "docker-compose.generated.yml", "down"],
            check=False
        )


class LocalGPUDeployer(BaseDeployer):
    """Deploy for local GPU (Apple Silicon or NVIDIA)."""

    def __init__(self, config: Config):
        """Initialize local GPU deployer."""
        super().__init__(config)
        self.processes = []

    def deploy_services(self) -> None:
        """Deploy services locally."""
        console.print("[cyan]Starting local GPU deployment...[/cyan]")

        # Start LLM service
        self._start_llm_service()

        # Start embedding service
        if self.config.services.embedding.provider == "local":
            self._start_embedding_service()

        # Start reranking service
        if self.config.services.reranking and self.config.services.reranking.enabled:
            self._start_reranking_service()

        # Start document processor
        if self.config.services.document_processor:
            self._start_doc_processor()

        # Start vector store
        self._start_vector_store()

        # Start main application
        self._start_main_app()

        # Start frontend
        self._start_frontend()

    def _start_llm_service(self) -> None:
        """Start LLM service based on provider."""
        provider = self.config.services.llm.provider

        if provider == "local-mlx":
            console.print("[cyan]Starting MLX server...[/cyan]")
            model_path = self.config.services.llm.mlx_model_path

            # Check if model exists
            if not Path(model_path).expanduser().exists():
                console.print(f"[yellow]⚠️  Model not found at {model_path}[/yellow]")
                console.print("Please download the model or use a different path")
                return

            # Start MLX server
            cmd = [
                "mlx_lm.server",
                "--model", model_path,
                "--host", "0.0.0.0",
                "--port", "8001"
            ]

            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=Path.cwd()
            )
            self.processes.append(("MLX Server", process))
            console.print("[green]✅ MLX server started on port 8001[/green]")

        elif provider == "vllm":
            console.print("[cyan]Starting vLLM server...[/cyan]")
            cmd = [
                "python", "-m", "vllm.entrypoints.openai.api_server",
                "--model", self.config.services.llm.model,
                "--port", "8001"
            ]

            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            self.processes.append(("vLLM Server", process))
            console.print("[green]✅ vLLM server started on port 8001[/green]")

        elif provider == "ollama":
            console.print("[cyan]Starting Ollama...[/cyan]")
            # Check if Ollama is running
            result = subprocess.run(
                ["ollama", "list"],
                capture_output=True,
                check=False
            )

            if result.returncode != 0:
                # Start Ollama service
                process = subprocess.Popen(
                    ["ollama", "serve"],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE
                )
                self.processes.append(("Ollama", process))
                time.sleep(3)  # Wait for service to start

            # Pull model if needed
            model = self.config.services.llm.model
            console.print(f"[cyan]Pulling Ollama model {model}...[/cyan]")
            subprocess.run(["ollama", "pull", model], check=False)

    def _start_embedding_service(self) -> None:
        """Start local embedding service."""
        console.print("[cyan]Starting embedding service...[/cyan]")

        # Start embedding service
        cmd = ["python", "services/embedding-service/app.py"]
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env={**os.environ,
                 "MODEL_NAME": self.config.services.embedding.model,
                 "DEVICE": self.config.services.embedding.device}
        )
        self.processes.append(("Embedding Service", process))
        console.print("[green]✅ Embedding service started on port 8002[/green]")

    def _start_reranking_service(self) -> None:
        """Start reranking service."""
        console.print("[cyan]Starting reranking service...[/cyan]")

        cmd = ["python", "services/reranking-service/app.py"]
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env={**os.environ,
                 "MODEL_NAME": self.config.services.reranking.model,
                 "DEVICE": self.config.services.reranking.device}
        )
        self.processes.append(("Reranking Service", process))
        console.print("[green]✅ Reranking service started on port 8004[/green]")

    def _start_doc_processor(self) -> None:
        """Start document processor service."""
        console.print("[cyan]Starting document processor...[/cyan]")

        cmd = ["python", "services/doc-processor/app.py"]
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        self.processes.append(("Doc Processor", process))
        console.print("[green]✅ Document processor started on port 8003[/green]")

    def _start_vector_store(self) -> None:
        """Start vector store service."""
        if self.config.services.vector_store.type == "chromadb":
            console.print("[cyan]Starting ChromaDB...[/cyan]")

            # Check if running in Docker
            result = subprocess.run(
                ["docker", "ps", "--filter", "ancestor=chromadb/chroma"],
                capture_output=True,
                check=False
            )

            if result.returncode != 0 or not result.stdout:
                # Start ChromaDB container
                subprocess.run([
                    "docker", "run", "-d",
                    "--name", "chromadb",
                    "-p", "8000:8000",
                    "-v", "chromadb-data:/chroma/chroma",
                    "-e", "IS_PERSISTENT=TRUE",
                    "chromadb/chroma"
                ], check=False)
                console.print("[green]✅ ChromaDB started on port 8000[/green]")

    def _start_main_app(self) -> None:
        """Start main FastAPI application."""
        console.print("[cyan]Starting main application...[/cyan]")

        cmd = [
            "uvicorn",
            "app.main:app",
            "--host", self.config.application.main_app.host,
            "--port", str(self.config.application.main_app.port),
            "--reload"
        ]

        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=Path("services/main-app")
        )
        self.processes.append(("Main App", process))
        console.print(f"[green]✅ Main app started on port {self.config.application.main_app.port}[/green]")

    def _start_frontend(self) -> None:
        """Start frontend development server."""
        console.print("[cyan]Starting frontend...[/cyan]")

        cmd = ["npm", "run", "dev"]
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=Path("frontend")
        )
        self.processes.append(("Frontend", process))
        console.print(f"[green]✅ Frontend started on port {self.config.application.frontend.port}[/green]")

    def check_health(self) -> Dict[str, bool]:
        """Check health of local services."""
        health_status = {}

        # Check processes
        for name, process in self.processes:
            health_status[name] = process.poll() is None

        # Check ports
        ports_to_check = {
            "LLM Service": 8001,
            "Embedding Service": 8002,
            "Doc Processor": 8003,
            "Reranking Service": 8004,
            "Main App": self.config.application.main_app.port,
            "Frontend": self.config.application.frontend.port
        }

        for service, port in ports_to_check.items():
            if self._check_port(port):
                health_status[service] = True

        return health_status

    def _check_port(self, port: int) -> bool:
        """Check if a port is open."""
        import socket
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex(('localhost', port))
        sock.close()
        return result == 0

    def cleanup(self) -> None:
        """Stop all local processes."""
        console.print("[yellow]Stopping local services...[/yellow]")
        for name, process in self.processes:
            if process.poll() is None:
                process.terminate()
                console.print(f"[yellow]Stopped {name}[/yellow]")


class UnifiedDeployer:
    """Main deployer that orchestrates deployment."""

    def __init__(self, config_path: Path):
        """Initialize unified deployer.

        Args:
            config_path: Path to configuration file
        """
        self.config_path = config_path
        self.config = None
        self.deployer = None

    def deploy(self) -> None:
        """Execute deployment."""
        try:
            # Load and validate configuration
            self._load_config()

            # Prepare environment
            self._prepare_environment()

            # Select and initialize deployer
            self._initialize_deployer()

            # Generate environment files
            self.deployer.generate_env_file()

            # Deploy services
            self.deployer.deploy_services()

            # Wait for services to start
            time.sleep(5)

            # Health check
            self._health_check()

            # Show access information
            self._show_access_info()

        except Exception as e:
            console.print(f"[red]❌ Deployment failed: {e}[/red]")
            if self.deployer:
                self.deployer.cleanup()
            raise

    def _load_config(self) -> None:
        """Load and validate configuration."""
        console.print("[cyan]Loading configuration...[/cyan]")

        loader = ConfigLoader()
        self.config = loader.load(self.config_path)

        # Validate
        validator = ConfigValidator()
        if not validator.validate(self.config):
            console.print("[red]Configuration validation failed:[/red]")
            console.print(validator.get_report())
            raise DeploymentError("Invalid configuration")

        console.print("[green]✅ Configuration loaded and validated[/green]")

    def _prepare_environment(self) -> None:
        """Prepare deployment environment."""
        console.print("[cyan]Preparing environment...[/cyan]")

        # Create necessary directories
        dirs = [
            "data/uploads",
            "data/documents",
            "data/processed",
            "models/embeddings",
            "models/reranking",
            "logs"
        ]

        for dir_path in dirs:
            Path(dir_path).mkdir(parents=True, exist_ok=True)

        console.print("[green]✅ Environment prepared[/green]")

    def _initialize_deployer(self) -> None:
        """Initialize the appropriate deployer."""
        deployment_type = self.config.deployment.type

        if deployment_type == "docker-compose":
            self.deployer = DockerComposeDeployer(self.config)
        elif deployment_type in ["local-gpu", "local-cpu"]:
            self.deployer = LocalGPUDeployer(self.config)
        else:
            raise DeploymentError(f"Unsupported deployment type: {deployment_type}")

        console.print(f"[green]✅ Initialized {deployment_type} deployer[/green]")

    def _health_check(self) -> None:
        """Perform health checks."""
        console.print("\n[cyan]Performing health checks...[/cyan]")

        max_retries = 10
        retry_delay = 3

        for attempt in range(max_retries):
            health_status = self.deployer.check_health()

            # Display status
            table = Table(title="Service Status")
            table.add_column("Service", style="cyan")
            table.add_column("Status", style="green")

            all_healthy = True
            for service, healthy in health_status.items():
                status = "✅ Running" if healthy else "⏳ Starting..."
                table.add_row(service, status)
                if not healthy:
                    all_healthy = False

            console.clear()
            console.print(table)

            if all_healthy:
                console.print("\n[green]✅ All services are healthy![/green]")
                break

            if attempt < max_retries - 1:
                time.sleep(retry_delay)
            else:
                console.print("\n[yellow]⚠️  Some services did not start properly[/yellow]")

    def _show_access_info(self) -> None:
        """Display access information."""
        panel = Panel.fit(
            f"[bold green]Deployment Successful![/bold green]\n\n"
            f"🌐 Frontend: http://localhost:{self.config.application.frontend.port}\n"
            f"🔧 API Docs: http://localhost:{self.config.application.main_app.port}/docs\n"
            f"📊 API Health: http://localhost:{self.config.application.main_app.port}/health\n\n"
            f"[dim]Configuration: {self.config.metadata.name}[/dim]\n"
            f"[dim]Environment: {self.config.deployment.environment}[/dim]",
            title="Access Information",
            border_style="green"
        )
        console.print(panel)

    def status(self) -> None:
        """Check deployment status."""
        if not self.config:
            self._load_config()
            self._initialize_deployer()

        health_status = self.deployer.check_health()

        table = Table(title="Service Status")
        table.add_column("Service", style="cyan")
        table.add_column("Status")

        for service, healthy in health_status.items():
            status = "[green]✅ Running[/green]" if healthy else "[red]❌ Stopped[/red]"
            table.add_row(service, status)

        console.print(table)

    def stop(self) -> None:
        """Stop deployment."""
        if not self.config:
            self._load_config()
            self._initialize_deployer()

        console.print("[yellow]Stopping deployment...[/yellow]")
        self.deployer.cleanup()
        console.print("[green]✅ Deployment stopped[/green]")


@click.command()
@click.option('--config', type=click.Path(exists=True), required=True,
              help='Path to configuration file')
@click.option('--preset', help='Use a preset configuration')
@click.option('--status', is_flag=True, help='Check deployment status')
@click.option('--stop', is_flag=True, help='Stop deployment')
def main(config, preset, status, stop):
    """Unified deployment script for Drass Compliance Assistant."""
    try:
        # Handle preset
        if preset:
            config_path = Path(f"deployment/configs/presets/{preset}.yaml")
            if not config_path.exists():
                console.print(f"[red]Preset not found: {preset}[/red]")
                sys.exit(1)
        else:
            config_path = Path(config)

        deployer = UnifiedDeployer(config_path)

        if status:
            deployer.status()
        elif stop:
            deployer.stop()
        else:
            deployer.deploy()

    except KeyboardInterrupt:
        console.print("\n[yellow]Deployment cancelled by user[/yellow]")
        sys.exit(0)
    except Exception as e:
        console.print(f"\n[red]Error: {e}[/red]")
        sys.exit(1)


if __name__ == "__main__":
    main()